fix rust-version compilation issue (#1335)
### What

Trying to regenerate the test wasms results in the following error.
```
error: failed to parse manifest at `/Users/siddharthsuresh/dev/rs-soroban-env/soroban-test-wasms/wasm-workspace/write_upgrade_bytes/Cargo.toml`

Caused by:
  error inheriting `rust_version` from workspace root manifest's `workspace.package.rust_version`

Caused by:
  `workspace.package.rust-version` was not defined
```

I think the issue has something to do with the limitations with
workspace inheritance, but I'm not really sure. @leighmcculloch please
let me know if you know of a better solution than just setting the
version again explicitly in each test wasm.